# github.com/go-task/task

version: '3'

vars:
  BINARY_NAME: registry-proxy
  VERSION: v0.1.0

tasks:
  run:
    env:
      REGISTRY_HOST: europe-docker.pkg.dev
      REPO_PREFIX: kubemq/images
      PORT: 8080
      HOST: 0.0.0.0
    cmds:
      - go run .
  docker:
    env:
      GOOS: linux
      GOARCH: amd64
    cmds:
      - go mod tidy
      - go mod vendor
      - docker build --build-arg VERSION={{.VERSION}} . -t europe-docker.pkg.dev/kubemq/images/{{.BINARY_NAME}}:{{.VERSION}}
      - docker tag europe-docker.pkg.dev/kubemq/images/{{.BINARY_NAME}}:{{.VERSION}} europe-docker.pkg.dev/kubemq/images/{{.BINARY_NAME}}:latest
  push:
    cmds:
      - docker push europe-docker.pkg.dev/kubemq/images/{{.BINARY_NAME}}:{{.VERSION}}
      - docker push europe-docker.pkg.dev/kubemq/images/{{.BINARY_NAME}}:latest
  deploy:
    cmds:
      - gcloud run deploy gcr-proxy --allow-unauthenticated --image "europe-docker.pkg.dev/kubemq/images/{{.BINARY_NAME}}:latest" --set-env-vars "REGISTRY_HOST=europe-docker.pkg.dev" --set-env-vars "REPO_PREFIX=kubemq/images"

#  curl -H "Authorization: Bearer ya29.a0AfB_byD5FHNVPCJAdqjAIssQt604bsJ4_FJROtVCNuRrupxbwJOK9XX9EInJ9Kt4bSLMOGGPGDKdLyILo_6jXq5Wrgc_EjAoEzz6huLnbf7AD_-fvI_e-p5Aam3epBUVj4G1muRLijTS7oXhSTgK1G44O6r4NQN-gyZszzBOt8YaCgYKAcQSARASFQHGX2MiFqAmuJbenHGnMZnKfO-4Bw0178" -H "Accept: application/vnd.docker.distribution.manifest.v2+json" "https://europe-docker.pkg.dev/v2/kubemq/images/manifests/latest"
